// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwFT-ti6k6b9fCKfvJEPspHI99g2-3Ies',
    appId: '1:647121967874:web:41fd59c0fde7626d4d001b',
    messagingSenderId: '647121967874',
    projectId: 'rock-music-assignment',
    authDomain: 'rock-music-assignment.firebaseapp.com',
    storageBucket: 'rock-music-assignment.firebasestorage.app',
    measurementId: 'G-CD643KK222',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMkZEPPbkKLUjgPwtXllCJFe_oj-AoRAw',
    appId: '1:647121967874:android:db15e698f44657414d001b',
    messagingSenderId: '647121967874',
    projectId: 'rock-music-assignment',
    storageBucket: 'rock-music-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7hcL1XhXhvlyrx6qsFFTSuteZaSUatlU',
    appId: '1:647121967874:ios:a8bf365cf32a994b4d001b',
    messagingSenderId: '647121967874',
    projectId: 'rock-music-assignment',
    storageBucket: 'rock-music-assignment.firebasestorage.app',
    iosBundleId: 'com.example.smartTripPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7hcL1XhXhvlyrx6qsFFTSuteZaSUatlU',
    appId: '1:647121967874:ios:a8bf365cf32a994b4d001b',
    messagingSenderId: '647121967874',
    projectId: 'rock-music-assignment',
    storageBucket: 'rock-music-assignment.firebasestorage.app',
    iosBundleId: 'com.example.smartTripPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwFT-ti6k6b9fCKfvJEPspHI99g2-3Ies',
    appId: '1:647121967874:web:d2e2095132824d144d001b',
    messagingSenderId: '647121967874',
    projectId: 'rock-music-assignment',
    authDomain: 'rock-music-assignment.firebaseapp.com',
    storageBucket: 'rock-music-assignment.firebasestorage.app',
    measurementId: 'G-W803W4MRGR',
  );
}
